var locations = [
    {
        "id": 1,
        "locationName": "The Junkyard grills, Central Area, Abuja.",
        "locationType": "indoor/outdoor",
        "mapURL": "https://maps.app.goo.gl/6VXHxodY4sh7df2D8",
        "affordability": 3.5,
        "rating": 4,
    },
    {
        "id": 2,
        "locationName": "The Pasha Restaurant, Maitama, Abuja.",
        "locationType": "indoor",
        "mapURL": "https://maps.app.goo.gl/7AoWut19kHiGSikHA",
        "affordability": 3,
        "rating": 4.5,
    },
    {
        "id": 3,
        "locationName": "The Milkshop and Breakfast company, Maitama, Abuja",
        "locationType": "indoor",
        "mapURL": "https://maps.app.goo.gl/zghgpdGb8MhVMeqH6",
        "affordability": 4.5,
        "rating": 3.5,
    },
    {
        "id": 4,
        "locationName": "Truck Central, Central Business District, Abuja",
        "locationType": "outdoor",
        "mapURL": "https://maps.app.goo.gl/Jo1d9Q1Yf151Edzq7",
        "affordability": 3,
        "rating": 4.5,
    },
    {
        "id": 5,
        "locationName": "Jabi Boat Club, Jabi, Abuja.",
        "locationType": "indoor/outdoor",
        "mapURL": "https://maps.app.goo.gl/Aq4e5SMusweSx3GC9",
        "affordability": 3.2,
        "rating": 4.7,
    },
    {
        "id": 6,
        "locationName": "Otega Restaurant 24/7, Wuse 2, Abuja.",
        "locationType": "indoor",
        "mapURL": "https://maps.app.goo.gl/uku2JnvzkMiQb7rr5",
        "affordability": 4,
        "rating": 4.7,
    },
    {
        "id": 7,
        "locationName": "Kebabs & Kurries, Wuse 2, Abuja",
        "locationType": "indoor",
        "mapURL": "https://maps.app.goo.gl/ZtdqfZdgYpHLNv7b8",
        "affordability": 4,
        "rating": 4.2,
    },
    {
        "id": 8,
        "locationName": "Ann's Restaurant & Bar, Maitama, Abuja",
        "locationType": "indoor",
        "mapURL": "https://maps.app.goo.gl/wVqdk2WPeWtTaSRZ6",
        "affordability": 4.1,
        "rating": 4.0,
    },

]